import { defineConfig } from '@adonisjs/vite'
import app from '@adonisjs/core/services/app'

const viteBackendConfig = defineConfig({
  /**
   * The output of vite will be written inside this
   * directory. The path should be relative from
   * the application root.
   */
  // buildDirectory: 'public/dist',

  /**
   * The path to the manifest file generated by the
   * "vite build" command.
   */
  manifestFile: app.inDev ? "this-vite-manifest-doesnt-exist.json":'public/dist/.vite/manifest.json',

  /**
   * Feel free to change the value of the "assetsUrl" to
   * point to a CDN in production.
   */
  assetsUrl: '/dist/assets',
})

export default viteBackendConfig
